/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Model.Graphs;
import Model.LineGraph;
import Model.RuntimeAttributes;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author sumit
 */
public class StatisticsPanel extends javax.swing.JPanel {

    private JPanel body;
    private List<Integer> deathGenotype;
    private List<Integer> popGenotype;
    private List<Integer> recoveredGenotype;
    private LineGraph deathDataset ;
    private LineGraph infectedDataset;
    private LineGraph recoveredDataset;
    
    /**
     * Creates new form StatisticsPanel
     */
    public StatisticsPanel(JPanel container, List<Integer> deathGenotype,List<Integer> recoveredGenotype,List<Integer> popGenotype,
    LineGraph deathDataset, LineGraph infectedDataset, LineGraph recoveredDataset ) {
        this.body=container;
        this.deathGenotype=deathGenotype;
        this.recoveredGenotype=recoveredGenotype;
        this.popGenotype=popGenotype;
        this.deathDataset=deathDataset;
        this.infectedDataset=infectedDataset;
        this.recoveredDataset=recoveredDataset;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        daysInfectedBtn = new javax.swing.JButton();
        daysRecoveryBtn = new javax.swing.JButton();
        variantsFitnessBtn = new javax.swing.JButton();
        deathsGenomeBtn = new javax.swing.JButton();
        popGenotypeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        recoveryGenomeBtn = new javax.swing.JButton();
        daysDeathsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("INFO 6205, Northeastern University. Summer, 2021");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Data points.gif"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        daysInfectedBtn.setBackground(new java.awt.Color(255, 193, 0));
        daysInfectedBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        daysInfectedBtn.setForeground(new java.awt.Color(102, 102, 102));
        daysInfectedBtn.setText("Days vs Infected");
        daysInfectedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysInfectedBtnActionPerformed(evt);
            }
        });
        add(daysInfectedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 230, -1));

        daysRecoveryBtn.setBackground(new java.awt.Color(255, 193, 0));
        daysRecoveryBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        daysRecoveryBtn.setForeground(new java.awt.Color(102, 102, 102));
        daysRecoveryBtn.setText("Days vs Recovery");
        daysRecoveryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysRecoveryBtnActionPerformed(evt);
            }
        });
        add(daysRecoveryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 230, -1));

        variantsFitnessBtn.setBackground(new java.awt.Color(255, 193, 0));
        variantsFitnessBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        variantsFitnessBtn.setForeground(new java.awt.Color(102, 102, 102));
        variantsFitnessBtn.setText("Variants vs Fitness");
        variantsFitnessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variantsFitnessBtnActionPerformed(evt);
            }
        });
        add(variantsFitnessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 230, -1));

        deathsGenomeBtn.setBackground(new java.awt.Color(255, 193, 0));
        deathsGenomeBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deathsGenomeBtn.setForeground(new java.awt.Color(102, 102, 102));
        deathsGenomeBtn.setText("Deaths Based on Genotype");
        deathsGenomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathsGenomeBtnActionPerformed(evt);
            }
        });
        add(deathsGenomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 230, -1));

        popGenotypeBtn.setBackground(new java.awt.Color(255, 193, 0));
        popGenotypeBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        popGenotypeBtn.setForeground(new java.awt.Color(102, 102, 102));
        popGenotypeBtn.setText("Population based on Genotype");
        popGenotypeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popGenotypeBtnActionPerformed(evt);
            }
        });
        add(popGenotypeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bar Graphs");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 350, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Line Graphs");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 350, 60));

        recoveryGenomeBtn.setBackground(new java.awt.Color(255, 193, 0));
        recoveryGenomeBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        recoveryGenomeBtn.setForeground(new java.awt.Color(102, 102, 102));
        recoveryGenomeBtn.setText("Recovery Based on Genotype");
        recoveryGenomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoveryGenomeBtnActionPerformed(evt);
            }
        });
        add(recoveryGenomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 230, -1));

        daysDeathsBtn.setBackground(new java.awt.Color(255, 193, 0));
        daysDeathsBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        daysDeathsBtn.setForeground(new java.awt.Color(102, 102, 102));
        daysDeathsBtn.setText("Days vs Deaths");
        daysDeathsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysDeathsBtnActionPerformed(evt);
            }
        });
        add(daysDeathsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void daysInfectedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysInfectedBtnActionPerformed
        // TODO add your handling code here:
        this.infectedDataset.display();
    }//GEN-LAST:event_daysInfectedBtnActionPerformed

    private void variantsFitnessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variantsFitnessBtnActionPerformed
        // TODO add your handling code here:
        Graphs demo = new Graphs("Variants vs Fitness","Variants", RuntimeAttributes.virusvariantLog);
        demo.displayDualAxis();
    }//GEN-LAST:event_variantsFitnessBtnActionPerformed

    private void deathsGenomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deathsGenomeBtnActionPerformed
        // TODO add your handling code here:
        Graphs demo = new Graphs("Deaths Based on Genotype","Deaths Based on Genotype",this.deathGenotype,this.recoveredGenotype,this.popGenotype);
        demo.displayDualAxis();
    }//GEN-LAST:event_deathsGenomeBtnActionPerformed

    private void popGenotypeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popGenotypeBtnActionPerformed
        // TODO add your handling code here:
        Graphs demo = new Graphs("Population Based on Genotype","Population Based on Genotype",this.deathGenotype,this.recoveredGenotype,this.popGenotype);
        demo.displayDualAxis();
    }//GEN-LAST:event_popGenotypeBtnActionPerformed

    private void recoveryGenomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoveryGenomeBtnActionPerformed
        // TODO add your handling code here:
        Graphs demo = new Graphs("Recovered Based on Genotype","Recovered Based on Genotype",this.deathGenotype,this.recoveredGenotype,this.popGenotype);
        demo.displayDualAxis();
    }//GEN-LAST:event_recoveryGenomeBtnActionPerformed

    private void daysDeathsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysDeathsBtnActionPerformed
        // TODO add your handling code here:
        this.deathDataset.display();
    }//GEN-LAST:event_daysDeathsBtnActionPerformed

    private void daysRecoveryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysRecoveryBtnActionPerformed
        // TODO add your handling code here:
        this.recoveredDataset.display();
    }//GEN-LAST:event_daysRecoveryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daysDeathsBtn;
    private javax.swing.JButton daysInfectedBtn;
    private javax.swing.JButton daysRecoveryBtn;
    private javax.swing.JButton deathsGenomeBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton popGenotypeBtn;
    private javax.swing.JButton recoveryGenomeBtn;
    private javax.swing.JButton variantsFitnessBtn;
    // End of variables declaration//GEN-END:variables
}
